apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
